# Generated by Django 4.1.7 on 2023-03-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('editora', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('manutencao', 'Em manutenção')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
    ]
